version: '3'
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - ..:/go/src/github.com/humbkr/albaplayer-server
        working_dir: /go/src/github.com/humbkr/albaplayer-server
        ports:
            - 8888
        # Make container run indefinitely
        command: "tail -f /dev/null"
