# General info.
APPName: Alba Player

# Database.
DB:
    Driver: sqlite3
    File: ./alba.db
Covers:
    #Directory: ./covers
    Directory: C:\Users\humbk\Pictures\alba_covers

# Logging system.
Log:
    File: app.log
    Path: ./

# Webserver configuration.
Server:
    Port: 8888

# Library configuration.
Library:
    #Folder: C:\Users\humbk\Music\alba-player\media
    Folder: D:\mp3
    # Preferred source for media cover image ("tag" or "file")
    CoverPreferredSource: tag
