

# General info.
APPName: Alba Player

# Database connection.
DB:
    Driver: sqlite3
    File: ./alba.db

# Logging system.
Log:
    File: app.log
    Path: ./

# Webserver configuration.
Server:
    Port: 8888

# Library configuration.
Library:
    Folder: C:\Users\humbk\Music\alba-player\media